package com.honeyai.service;

import com.honeyai.exception.PdfGenerationException;
import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Path;

/**
 * Service for PDF document generation using Apache PDFBox.
 * Foundation service for label generation feature.
 */
@Service
@Slf4j
public class PdfService {

    /**
     * Creates a new empty PDF document.
     * Caller is responsible for closing the document.
     *
     * @return new PDDocument instance
     */
    public PDDocument createDocument() {
        return new PDDocument();
    }

    /**
     * Creates a new page with the specified size.
     *
     * @param pageSize the page dimensions (e.g., PDRectangle.A4)
     * @return new PDPage with specified size
     */
    public PDPage createPage(PDRectangle pageSize) {
        return new PDPage(pageSize);
    }

    /**
     * Creates a new A4-sized page.
     *
     * @return new PDPage with A4 dimensions (595 x 842 points)
     */
    public PDPage createA4Page() {
        return createPage(PDRectangle.A4);
    }

    /**
     * Adds text to a page at the specified coordinates.
     * Coordinates origin is bottom-left corner of the page.
     *
     * @param document the PDF document
     * @param page     the page to add text to
     * @param text     the text to write
     * @param x        x coordinate in points (from left)
     * @param y        y coordinate in points (from bottom)
     * @param fontSize font size in points
     */
    public void addTextToPage(PDDocument document, PDPage page, String text, float x, float y, float fontSize) {
        try (PDPageContentStream contentStream = new PDPageContentStream(
                document, page, PDPageContentStream.AppendMode.APPEND, true, true)) {

            PDType1Font font = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            contentStream.beginText();
            contentStream.setFont(font, fontSize);
            contentStream.newLineAtOffset(x, y);
            contentStream.showText(text);
            contentStream.endText();

        } catch (IOException e) {
            throw new PdfGenerationException("Failed to add text to page: " + e.getMessage(), e);
        }
    }

    /**
     * Adds text to a page with bold font.
     *
     * @param document the PDF document
     * @param page     the page to add text to
     * @param text     the text to write
     * @param x        x coordinate in points
     * @param y        y coordinate in points
     * @param fontSize font size in points
     */
    public void addBoldTextToPage(PDDocument document, PDPage page, String text, float x, float y, float fontSize) {
        try (PDPageContentStream contentStream = new PDPageContentStream(
                document, page, PDPageContentStream.AppendMode.APPEND, true, true)) {

            PDType1Font font = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);

            contentStream.beginText();
            contentStream.setFont(font, fontSize);
            contentStream.newLineAtOffset(x, y);
            contentStream.showText(text);
            contentStream.endText();

        } catch (IOException e) {
            throw new PdfGenerationException("Failed to add bold text to page: " + e.getMessage(), e);
        }
    }

    /**
     * Generates a test PDF with sample text.
     * Used to verify PDFBox setup is working correctly.
     *
     * @param outputPath path where the PDF will be saved
     */
    public void generateTestPdf(Path outputPath) {
        log.info("Starting test PDF generation to: {}", outputPath);

        try (PDDocument document = createDocument()) {
            PDPage page = createA4Page();
            document.addPage(page);

            // Add test text
            addTextToPage(document, page, "HoneyAI Test PDF", 50, 750, 24);
            addTextToPage(document, page, "This is a test document generated by PdfService.", 50, 700, 12);
            addTextToPage(document, page, "Apache PDFBox 3.0.1 is working correctly.", 50, 680, 12);

            document.save(outputPath.toFile());
            log.info("Test PDF generation completed successfully: {}", outputPath);

        } catch (IOException e) {
            log.error("Failed to generate test PDF: {}", e.getMessage(), e);
            throw new PdfGenerationException("Failed to generate test PDF: " + e.getMessage(), e);
        }
    }

    /**
     * Generates a test PDF with default output path ./test-output.pdf
     */
    public void generateTestPdf() {
        generateTestPdf(Path.of("./test-output.pdf"));
    }

    /**
     * Converts millimeters to PDF points.
     * 1 point = 1/72 inch, 1 inch = 25.4 mm
     * Therefore: 1 mm = 72/25.4 = 2.83465 points
     *
     * @param mm value in millimeters
     * @return value in points
     */
    public float mmToPoints(float mm) {
        return mm * 2.83465f;
    }

    /**
     * Converts points to millimeters.
     *
     * @param points value in points
     * @return value in millimeters
     */
    public float pointsToMm(float points) {
        return points / 2.83465f;
    }
}
